### ISSUE TITLE
multiple frontends connected to same server

### ISSUE THREAD

**Issue by klaus1978** [feathersjs-ecosystem/feathers-vuex#457] opened 2020-04-01 07:01 UTC
Hey folks,
I try to connect my 
ADMIN frontend (localhost:3000) and my 
USERs frontend (localhost:8000) to the same
 feathers server (localhost:3030).

ADMIN is a nuxt SPA app, USERs a UNIVERSAL app. (But I also tried 2 SPAs)

Each frontend works fine as long as they run exclusively. 
In the moment both frontends are running and I try to log in to one of them I get TIMEOUT errors when trying to authenticate:

> "timeout of 5000ms exceeded calling create on authentication"

In the moment I disable one of my frontends again, the timeout errors disappear and logging in is possible again.

Thanks a lot for helping
Klaus

**Comment by litti** [comment] 2020-04-02 17:25
Hi Klaus, can you show us some (abstract) code or do you have a small example project which shows the error?

**Comment by klaus1978** [comment] 2020-04-02 18:40
Hey Andre, 
thanks a  lot for responding. Hm, as far as I see, I am following the documentation when creating the app(s). I might build a sample but need some time for it.

What i found out today: 
I have a big delay between the authentication before hook and the after hook on server side
```
 app.service('authentication').hooks({
    before: {
      all: [context => {
        console.log('before', context);

(1)        if (context.method === 'create' && context.params.user) context.params.user = null;
        return context;

      }]
    },
    after: {
      all: [context => {
        console.log(' After', context);
      }],
      create: [
        async (context) => {

          await context.app.service('users').patch(context.result.user._id, {
            lastLogin: new Date()
          });

          return context;
        }
      ]
    },
    error: {
      all: [context => {
        console.log('auth ERR', context);
      }]
    },
```
Again, in the moment when I disable 1 frontend app, it seems to work quite well. Is it possible to set timeout for authentication to maybe 10000? Where would I do that?

Another thing that might be related: I realized that I get "Invalid login" error when I logout (myuser1) from my frontend and try to login with myuser2.
I saw on server side that the before context still had context.user set to my myuser1. That's why I added (1).
I am pretty sure that at least this behavior is new after I upgraded from 3.8 to 3.9
Best wishes

**Comment by litti** [comment] 2020-04-02 21:53
Which authentication methods do you use? Maybe it's related to jwt and storing the jwt for both backends in the same place (jwt2 overwriting jwt1 or jwt1 is used instead of jwt2)

**Comment by marshallswain** [comment] 2020-04-03 03:49
Definitely a weird issue.  I run Gridsome and Vue CLI apps at the same time with zero configuration over the normal Feathers server code.

**Comment by klaus1978** [comment] 2020-04-03 06:38
Hey again, 
I am using jwt, yep! and the idea was to have 1 server talking to 2 different frontend apps (ADMIN and USER). So I do not use microservices as you was asking, Andre.

The flow currently looks like following:

Frontend: I try to login from one of my frontend Apps
Server:     before hook fires
Frontend: I get timeout error
Server:     after hook fires --> also channel login hook fires

I just still don't understand why then my 2 frontend apps are up, I have this big delay between before and after hook. (My data is stored in Mongo DB ATLAS)
Any possibility to increase TIMEOUT value for authentication? I already tried on the client:

```
import feathersClient, {
  makeServicePlugin,
  BaseModel
} from "../../feathers-client";

class AuthManagement extends BaseModel {
  constructor(data, options) {
    super(data, options);
  }

  // Required for $FeathersVuex plugin to work after production transpile.
  static modelName = "AuthManagement";
  // Define default properties here
  //   static instanceDefaults() {
  //     return {

  //     };
  //   }
}
const servicePath = "authManagement";
feathersClient.service(servicePath).timeout = 10000;
const servicePlugin = makeServicePlugin({
  enableEvents: false,
  Model: AuthManagement,
  service: feathersClient.service(servicePath),
  servicePath
});

export default servicePlugin;
```
But I still get the error telling me "Timeout after 5000 ms" so I am not sure if this is the correct place to configure the timeout?
Best klaus

**Comment by marshallswain** [comment] 2020-05-02 17:44
@klaus1978 were you ever able to figure out the cause of this?  I'm currently running four client apps on the same server without any delay.  I'm using feathers-auth0 for auth, though, so maybe this issue is in the latest auth plugin?

**Comment by klaus1978** [comment] 2020-05-03 07:53
Hey, unfortunatelly no. I just recreated the server from scratch (with v4 only) as my old server was v3 and migrated- so maybe this had an effect as well. I will need a couple of days I guess, and report if this helped...

**Comment by marshallswain** [comment] 2020-09-02 20:17
I'm going to close this one since it hasn't seen any activity for a while.  Please reopen if you are able to isolate and reproduce the issue.

**Closed by marshallswain** 2020-09-02 20:17 UTC
