### ISSUE TITLE
[vuex] do not mutate vuex store state outside mutation handlers

### ISSUE THREAD

**Issue by akvaliya** [feathersjs-ecosystem/feathers-vuex#434] opened 2020-02-26 12:04 UTC
### Steps to reproduce

Create chat app in nuxt by following [these steps](https://vuex.feathersjs.com/common-patterns.html#full-nuxt-example). 

Below if code of file in which i am facing the issue.

```
<template>
  <form class="flex flex-row flex-space-between" @submit.prevent="onSubmit">
    <input v-model="message.text" type="text" class="flex flex-1" />
    <button class="button-primary" type="submit">Send</button>
  </form>
</template>

<script>
import { ref } from '@vue/composition-api'
export default {
  name: 'MessageComposer',
  setup(props, context) {
    const { Message } = context.root.$FeathersVuex.api;
    const message = ref(new Message({ text: '' }));
    function reset() {
      message.value = new Message({ text: '' });
    }
    function onSubmit() {
      if (!message.value.text) { return; };
      message.value.save();
      reset();
    }

    return { message, reset, onSubmit }
  }
}
</script>

```

### Expected behavior
It should work without any errors in **strict mode** too. 

### Actual behavior
It gives this error on v-model change. 

For resolving this error i had to add `export const strict = false` in `services/index.js`

I am using suggested syntax in nuxt-full-example instead of exporting vuex store.

### System configuration
**feathers-vuex**: 3.6.1
**@vue/composition-api**: 0.3.4
**vuex**: 3.1.2

**Comment by itoonx** [comment] 2020-03-02 18:02
The problem is your ```store/index.js``` 
It should be like this, Please check if you're using createStore may be is deprecated in this version

```
const requireModule = require.context(
  // The path where the service modules live
  './services',
  // Whether to look in subfolders
  false,
  // Only include .js files (prevents duplicate imports`)
  /.js$/
)
const servicePlugins = requireModule
  .keys()
  .map(modulePath => requireModule(modulePath).default)

export const state = () => ({
  // Set animate transition
  transition: 'fade-in-up'
})

export const mutations = {
  // Set page transition
  SET_TRANSITION (state, transition) {
    state.transition = transition
  }
}

export const actions = {
  nuxtServerInit ({ commit, dispatch }, { req }) {
    return initAuth({
      commit,
      dispatch,
      req,
      moduleName: 'auth',
      cookieName: 'feathers-jwt'
    })
  },
  nuxtClientInit ({ state, dispatch, commit }, context) {
    hydrateApi({ api: models.api })
    // Run the authentication with the access token hydrated from the server store
    if (state.auth.accessToken) {
      return dispatch('auth/onInitAuth', state.auth.payload)
    }
  }
}

export const getters = {}

export const plugins = [
  ...servicePlugins,
  auth
]
```

**Comment by akvaliya** [comment] 2020-03-03 10:01
@itoonx  Nope. I am not using createStore. Like i said in question i have followed [these steps](https://vuex.feathersjs.com/common-patterns.html#full-nuxt-example) . So my `store/index.js` is exactly like you have suggested(last code block in example link).

**Comment by marshallswain** [comment] 2020-03-10 00:16
@akvaliya this error is happening because you are binding the input directly to the store:

```
v-model="message.text"
```

In the above, `message` is a record in the store.  To make the error go away, use the clone and commit pattern.

```
// In the template
v-model="messageClone.text"

// Before rendering the template
messageClone = message.clone()
```

**Comment by marshallswain** [comment] 2020-03-14 17:29
Closing for now.  Feel free to reopen.

**Closed** 2020-03-14 17:29 UTC
Labels: question

**Comment by tkssharma** [comment] 2021-04-17 13:05
`vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in callback for watcher "function () { return this._data.$$state }": "Error: [vuex] do not mutate vuex store state outside mutation handlers."`

----- LONG STACK TRACE ----- 
could have been helpful if i know which store property is creating this issue
